apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: wordpress.pilotgapps.com
      http:
        paths:
          - backend:
              serviceName: wordpress
              servicePort: 80
          - path: /phpmyadmin
            backend:
              serviceName: phpmyadmin
              servicePort: 80
  # This section is only required if TLS is to be enabled for the Ingress
  # tls:
  #     - hosts:
  #         - www.example.com
  #       secretName: example-tls

  # If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: example-tls
  #   namespace: foo
  # data:
  #   tls.crt: <base64 encoded cert>
  #   tls.key: <base64 encoded key>
  # type: kubernetes.io/tls          